---
# tasks file for postgres

- name: copy systmd unit file
  template: src=redis.service.j2 dest=/etc/systemd/system/redis.service mode=0755

- name:  Make sure a service is running
  systemd: 
    state: restarted 
    name: redis
    enabled: yes